In [6]:
import numpy as np

A = np.array([1,2,3,4])
np.ndim(A)
A.shape

B = np.array([[1,2], [3, 4], [5, 6]])
np.ndim(B)
B.shape

1


(3, 2)

In [3]:
import numpy as np

A = np.array([[1,2,3], [4,5,6]])
B = np.array([7,8,9])
C = np.array([[7],[8],[9]])

np.dot(A, B)
np.dot(A, C)

array([[ 50],
       [122]])

In [12]:
X = np.array([1, 2])
W = np.array([[1, 3, 5 ], [2, 4, 6]])

Y = np.dot(X, W)
print(Y)

[ 5 11 17]


In [14]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([1, 2, 3])

A1 = np.dot(X, W) + B1
print(A1)

[ 3.  7. 11.]


In [18]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def init_network():
  network = {}
  network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
  network['b1'] = np.array([0.1, 0.2, 0.3])
  network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
  network['b2'] = np.array([0.1, 0.2])
  network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
  network['b3'] = np.array([0.1, 0.2])

  return network


def forward(network, x):
  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']

  a1 = np.dot(x, W1) + b1
  z1 = sigmoid(a1)

  a2 = np.dot(z1, W2) + b2
  z2 = sigmoid(a2)

  a3 = np.dot(z2, W3) + b3
  y = a3
  return y


network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[0.31682708 0.69627909]
