In [2]:
import numpy as np

x = np.array([1,2,3])
y = np.array([4,5,6])

m = np.array([x, y])
m.shape

(2, 3)

In [6]:
import numpy as np
n = np.arange(0, 30, 2)

n = n.reshape(3, 5)

k = np.linspace(0, 9, 6)

k.resize(3, 2)

1-------------------
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
2-------------------
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
3-------------------
[0.  1.8 3.6 5.4 7.2 9. ]
4-------------------
[[0.  1.8]
 [3.6 5.4]
 [7.2 9. ]]


In [21]:
np.ones([2, 3])
np.zeros([2,3])
np.eye(3)
np.diag([1,2,3,4])
np.array([1,2,3] * 2)
np.repeat([1,2,3], 2)
np.repeat([[1,2], [3,4]], 2)
np.repeat([[1,2], [3,4]], 2, axis=0)
np.repeat([[1,2], [3,4]], 2, axis=1)



array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [23]:
p = np.ones([2, 3], int)
np.vstack([p, 2*p])
np.hstack([p, 2*p])


array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [27]:
x = np.array([1,2,3])
y = np.array([4,5,6])

x * y
x + y
x ** 2
x.dot(y)


32

In [29]:
y = np.array([4,5,6])
z = np.array([y, y**2])
z.shape
z.T.shape



(3, 2)

In [32]:
a = np.array([-4, -3, 1, 0, 5])
a.sum()
a.max()
a.min()
a.mean()

a.argmax()
a.argmin()


0

In [33]:
s = np.arange(13) ** 2
s[0]
s[5]
s[0:3]
s[-3:]
s[-4::-3]

array([0, 1, 4], dtype=int32)

In [34]:
r = np.arange(36)
r.resize(6,6)

r[3, 3:6]
r[:, 3:6]
r[r > 31]
r[r > 31] = 0

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [35]:
r = np.arange(36)
r.resize(6,6)

r2 = r[:3, :3]
r2[:] = 1
r


array([[ 1,  1,  1,  3,  4,  5],
       [ 1,  1,  1,  9, 10, 11],
       [ 1,  1,  1, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:

r = np.arange(36)
r.resize(6,6)

r_copy = r.copy()
r_copy[:] = 5
r


In [39]:
mylist = np.random.randint(0, 10, (4, 3))

for row in mylist:
    print(row)

for i, row in enumerate(mylist):
    print('row', i, 'is', row)


mylist2 = mylist**2

for i, j in zip(mylist, mylist2):
    print(i, '+', j, '=', i + j)

[3 3 5]
[8 8 5]
[8 2 4]
[7 3 5]
row 0 is [3 3 5]
row 1 is [8 8 5]
row 2 is [8 2 4]
row 3 is [7 3 5]
[3 3 5] + [ 9  9 25] = [12 12 30]
[8 8 5] + [64 64 25] = [72 72 30]
[8 2 4] + [64  4 16] = [72  6 20]
[7 3 5] + [49  9 25] = [56 12 30]
